# Coder's Note:
# This script reads the CSV of store URLs generated by the sitemap_scraper.py
# and uses Playwright to visit each URL, click "Start Your Order", and
# extract the final store ID. This version removes the unnecessary wait after clicking.
# Last checked: September 15, 2025
# Coder's Note:
# This script is the previous working version with two key changes:
# 1. The regex for store IDs now accepts letters and numbers.
# 2. It is configured to run on a small test CSV for fast debugging.
# Coder's Note:
# This version uses a corrected locator strategy based on the user's
# successful debugging. It now looks for a link that contains an address.
# Last checked: September 16, 2025

import re
import time
import csv
import argparse
from pathlib import Path
from playwright.sync_api import sync_playwright

from macrobell.config import CHUNKS_DIR

def main():
    """
    Reads a list of store URLs from a CSV, visits each one to find the
    store ID and full address, and saves the enriched data to a new CSV.
    """
    parser = argparse.ArgumentParser(description="Scrape store IDs for a specific chunk of stores.")
    parser.add_argument("--chunk", type=int, required=True, help="The chunk number to process (e.g., 1).")
    args = parser.parse_args()

    # Dynamically construct file paths based on the chunk number
    input_filename = Path(CHUNKS_DIR) / f"chunk_{args.chunk:02d}.csv"
    output_filename = Path(CHUNKS_DIR) / f"chunk_{args.chunk:02d}_with_ids.csv"
    
    stores_to_process = []
    try:
        with open(input_filename, mode='r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            for row in reader:
                stores_to_process.append(row)
    except FileNotFoundError:
        print(f"ERROR: The input file '{input_filename}' was not found.")
        print("Please run chunk_stores.py first.")
        return
        
    print(f"Found {len(stores_to_process)} stores to process from '{input_filename}'.")
    
    stores_with_ids = []

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36")
        page = context.new_page()

        try:
            for i, store_data in enumerate(stores_to_process):
                store_url = store_data['url']
                print(f"\nProcessing store {i+1}/{len(stores_to_process)}: {store_url}")

                try:
                    page.goto(store_url, timeout=60000)

                    try:
                        cookie_button = page.get_by_role("button", name=re.compile("accept|agree", re.IGNORECASE))
                        cookie_button.wait_for(state="visible", timeout=5000) 
                        cookie_button.click()
                        cookie_button.wait_for(state="hidden", timeout=5000)
                    except Exception:
                        pass # No cookie banner found, continue
                    
                    # --- THE FIX: Use the locator strategy you discovered ---
                    print(" - Finding address link on page...")
                    # This finds a link whose name/text contains a 5-digit number (the zip code).
                    # This is a robust way to identify the address link.
                    address_locator = page.get_by_role("link", name=re.compile(r"\d{5}"))
                    address_locator.wait_for(state="visible", timeout=10000)
                    full_address = address_locator.inner_text()
                    
                    zip_code_match = re.search(r'(\d{5})', full_address)
                    zip_code = zip_code_match.group(1) if zip_code_match else "N/A"
                    print(f" - Found Zip Code: {zip_code}")
                    
                    store_data['full_address'] = full_address.replace('\n', ', ')
                    store_data['zip_code'] = zip_code

                    # --- Find Store ID ---
                    start_order_link = page.get_by_role("link", name="Start Your Order")
                    start_order_link.wait_for(state="visible", timeout=15000)
                    start_order_link.click()
                    
                    page.wait_for_load_state("load", timeout=15000)
                    final_url = page.url
                    
                    store_id_match = re.search(r"store=([\w]+)", final_url)
                    store_id = store_id_match.group(1) if store_id_match else "N/A"
                    print(f" - Found Store ID: {store_id}")

                    store_data['store_id'] = store_id
                    stores_with_ids.append(store_data)

                except Exception as e:
                    print(f" - FAILED to process this store: {e}")
                    store_data['store_id'] = 'ERROR'
                    store_data['full_address'] = 'ERROR'
                    store_data['zip_code'] = 'ERROR'
                    stores_with_ids.append(store_data)
                    continue

        except Exception as e:
            print(f"\nA critical error occurred: {e}")
        finally:
            print("--- Closing browser ---")
            browser.close()

    # --- SAVE FINAL RESULTS TO A NEW CSV ---
    if stores_with_ids:
        print(f"\n--- Saving {len(stores_with_ids)} stores with IDs to {output_filename} ---")
        fieldnames = ['url', 'state', 'city', 'address_slug', 'store_id', 'full_address', 'zip_code']
        with open(output_filename, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=fieldnames, extrasaction='ignore')
            writer.writeheader()
            writer.writerows(stores_with_ids)
        print("Successfully saved final store data.")

if __name__ == "__main__":
    main()
